version: '3'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3307"

  # Node.js service
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_container
    ports:
      - "8800:8800"
    depends_on:
      - mysql
